### ISSUE TITLE
[Suggestion] Alternatives to 'They Said So'

### ISSUE THREAD

**Issue by MustaDevelop** [the-wright-jamie/tab-nine#135]
Hello!
I've been using this extension for a while and I can say it's a great successor to Tabliss. While I believe that, I wanted to help on something, and decided to find an alternative to They Said So.

### Number 1: Quotable

[Quotable](https://github.com/lukePeavey/quotable) is an Open-Source API, which I can guarantee it's a plus for at least some of you. The only problem is that it has a rate limit of 180 requests per minute. So if so many people are using it, ~~that would be an issue.~~ Future Self: I was wrong.

### Number 2: API Ninjas

[API Ninjas](https://api-ninjas.com/) is an API that has over 78 data APIs. This is perfect if quotes isn't the only thing you want to add.
And even if quotes is the only thing you want, there's so many of them. _I think that's only a plus in my book._
It's sadly not Open-Source, so there's a chance they might go the same way as They Said So. But for now that doesn't seem to be the plan.

And that's all I could find! If there are other APIs I missed, feel free to tell me in the comments.
_Man, I feel like a weirdo for focusing so much on quotes._

**Comment by the-wright-jamie** [comment]
Hey, thank you for this suggestion.

~~If Quotable is open source, that would mean that I could run my own instance of it on a private server, right? As it so happens, I have a server that I use to run <https://troll.xsfs.xyz/image.png>. If I have time (which is very little right now, unfortunately - I can't give Tab Nine as much time as I would like) I could spin up an instance of it with no problem.~~

Quotable says it's 180 requests per minute, **per IP address**, so using it is viable actually - it'll be based on per user rather than the project as a whole.

Future note: currently thinking this should be done alongside, and not instead of, #80. Having the ability to add custom quotes alongside an option to use 'online' quotes would be good. The goal of this fork is to further extend the customisablilty of Tabliss which means both are within scope.

### P.S.

> _Man, I feel like a weirdo for focusing so much on quotes._

Nah, don't worry, the quotes are cool - I appreciate the suggestion. Just wish there were more than 24 hours in a day, and I didn't need 8 of them asleep in order to be a (somewhat functional) person.

**Comment by MustaDevelop** [comment]
> Quotable says it's 180 requests per minute, per IP address, so using it is viable actually - it'll be based on per user rather than the project as a whole.

That's how it works? I somehow never thought of it that way.

**Comment by the-wright-jamie** [comment]
Yeah "per IP address" = "per user" (basically). That makes this a little easier 😛.

**Comment by 7Pawns** [comment]
Is this still relevant? Quotable seems to work fine, tested it on my fork

**Comment by the-wright-jamie** [comment]
Fixed in #147 - thank you @7Pawns. This will be released in next release (hopefully before the weekend)
