### ISSUE TITLE
IP info issue

### ISSUE THREAD

**Issue by kotobuki09** [the-wright-jamie/tab-nine#71]
I have an issue with the IP info didn't show up at all anywhere on the page. Could you check on this?

**Comment by the-wright-jamie** [comment]
Hi! We will need some extra info. Some screenshots would be nice. As we are dealing with IP addresses, please make sure you censor any sensitive information sufficiently (blur will not suffice, please use black bar censorship).

Please also specify your browser, and if you are using a VPN, as using anything other than the officially support Chrome or Firefox might be causing issues 

Please also check your display and font settings, as well as any custom CSS you might have specified.

**Comment by the-wright-jamie** [comment]
Ok, so I was able to test this myself just now - it is indeed broken. I'll see what I can do. Thank you for reporting!

**Comment by the-wright-jamie** [comment]
![image](https://github.com/the-wright-jamie/tab-nine/assets/121819290/38c80f76-cfca-40fe-8ad4-1c58863ca7b0)

**Comment by the-wright-jamie** [comment]
This service was updated in 7dd413cb47e8de6648be3f6c65d36774e4319e05, during Tabliss' development - however this is around the same time the developer of that project stopped being active, and the last build on stores for Tabliss is before the date of this commit. Perhaps reverting it is the answer? It was changed because of https://github.com/joelshepherd/tabliss/issues/482, but after some research I have found that this project (https://www.gogeoip.com/) is back online so we should be able to use this again. https://web.tabliss.io/ also uses this, so it appears to be fixed whatever the issue was back then.

@Tanza3D you created that issue, have you had any further issues with the IP Info plugin? The latest build of Tabliss isn't using this, so you've been using that service it seems this whole time. https://ipwho.is/ isn't working because of a CORS issue, which I'm not sure if I can fix from this end. Just wondering if you had any ideas.

**Comment by the-wright-jamie** [comment]
# Suggested Resolution
This is the fix that's going to be implemented

Revert 7dd413cb47e8de6648be3f6c65d36774e4319e05 and go back to using the old method until it breaks again, at that point research what needs to be done to fix it.

**Comment by the-wright-jamie** [comment]
Fix coming out soon, new version being submitted to stores

**Comment by kotobuki09** [comment]
"That's great, thank you! I was wondering if there are any plans to include an offline quotes feature or a manual quote adding function to replace the 'They said so' feature. Personally, I find the current developer quotes and jokes not quite enjoyable."

**Comment by the-wright-jamie** [comment]
Currently, it's not planned. You've probably seen #29, the API is paid now. Certainly, you should open a feature request issue so it's at least in the backlog. I can understand if they are not quite enjoyable, they aren't for everyone. Just to make you aware, the Jokes API has other jokes, not just programming ones. 

I may take a look at [this fork](https://github.com/Mv0sKff/tabliss_offline_quotes) and see how it works, or as you say provide a way of uploading manual quotes. I'm quite busy IRL, but I'm aiming to create at least one new feature for Tab Nine a month (when I forked Tabliss, I was not busy, and I didn't expect to be for a while so that's why I'm in this situation). PRs are much appreciated, so if you've got time or abilitiy to give it a try please do.

**Comment by kotobuki09** [comment]
For sure! I am trying to take a look at that if I can see how the offline quote working.

**Comment by the-wright-jamie** [comment]
Please take a look at that fork, specifically, this commit: 9dd7529c19c2acc857cd9425be81d7f66af27caf. You should be able to pull something off like that, or you could have a way for something to 'upload' a CSV, JSON or TXT file. That would be the preferred implementation in my opinion.

**Comment by Tanza3D** [comment]
i think a good way to fix this is to have a list of multiple services to use, falling back when one can't be reached, so there's no need to keep changing them when they break, but truly the best solution would be to get the ip directly without having to use an external service, or host your own which you know won't break

**Comment by Tanza3D** [comment]
cloudflare might be a good choice, they don't usually break - https://www.cloudflare.com/cdn-cgi/trace

**Comment by kotobuki09** [comment]
What are you suggesting for services? @Tanza3D  I take a look around but most of them require pay to access API now. Some free tier is unusable

**Comment by Tanza3D** [comment]
to get ip info
